### ISSUE TITLE
configmenu poping

### ISSUE THREAD

**Issue by Mattudw** [fuyuneko/startpage#3]
Hi men,
You did a really great job here, i literally love it, so simple but so good.
But I have one shitty problem, I don't have cookies or any other craps like that and thank's to firefox I'm 24/7 in private mode but that's the problem, because of that your startpage poping continually (every 20mn I guess) your configmenu, it's soo boring... Is there a way to totally disable it and automaticly use the config.json ?

**Comment by fuyuneko** [comment]
Pull request https://github.com/fuyuneko/startpage/pull/4
